"""Add agent_graphs table

Revision ID: 812ba4d72478
Revises: 9077b9149369
Create Date: 2026-02-01 17:23:35.021511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '812ba4d72478'
down_revision: Union[str, None] = '9077b9149369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_graphs',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_nickname', sa.String(), nullable=False),
    sa.Column('mermaid_diagram', sa.Text(), nullable=False),
    sa.Column('graph_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('edge_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_graphs')
    # ### end Alembic commands ###
